# Generated by Django 2.1.4 on 2019-01-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=32, unique=True)),
                ('module_create_time', models.DateTimeField(auto_now_add=True)),
                ('statement', models.TextField()),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tTitle', models.CharField(max_length=32)),
                ('tBody', models.TextField()),
                ('tCreate_time', models.DateTimeField(auto_now_add=True)),
                ('tViews', models.PositiveIntegerField(default=0)),
                ('tID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS_index.Module')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ('-tCreate_time',),
            },
        ),
    ]
