# Generated by Django 2.1.4 on 2019-01-24 06:52

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('BBS_index', '0002_topic_tuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
