# Generated by Django 2.1.4 on 2018-12-25 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uservideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=128)),
                ('video_create_time', models.DateTimeField(default=datetime.datetime(2018, 12, 25, 12, 10, 40, 692990, tzinfo=utc))),
                ('video_path', models.CharField(max_length=256)),
                ('video_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'ordering': ('video_create_time',),
            },
        ),
    ]
