# Generated by Django 2.1.4 on 2018-12-25 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 13, 3, 23, 488192, tzinfo=utc)),
        ),
    ]
