# Generated by Django 2.1.4 on 2019-01-03 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0003_auto_20190103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 4, 56, 7, 520416, tzinfo=utc)),
        ),
    ]
