# Generated by Django 2.1.4 on 2019-01-11 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0005_auto_20190111_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 11, 6, 48, 14, 402363, tzinfo=utc)),
        ),
    ]
