# Generated by Django 2.1.4 on 2019-01-17 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0006_auto_20190111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 8, 12, 10, 801911, tzinfo=utc)),
        ),
    ]
