# Generated by Django 2.1.4 on 2019-01-17 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0007_auto_20190117_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 8, 13, 35, 746856, tzinfo=utc)),
        ),
    ]
