# Generated by Django 2.1.4 on 2019-01-23 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0010_auto_20190123_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservideo',
            options={'ordering': ('video_create_time',), 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 6, 33, 25, 230298, tzinfo=utc)),
        ),
    ]
