# Generated by Django 2.1.4 on 2019-01-24 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uservideo', '0012_auto_20190123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 6, 51, 48, 448161, tzinfo=utc)),
        ),
    ]
