# Generated by Django 2.1.4 on 2018-12-24 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0004_auto_20181224_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalvideo',
            name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 8, 21, 39, 678020, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='PersonalVideo',
        ),
    ]
