# Generated by Django 2.1.4 on 2018-12-25 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0013_auto_20181224_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 12, 10, 40, 680405, tzinfo=utc)),
        ),
    ]
