# Generated by Django 2.1.4 on 2019-01-03 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0015_auto_20181225_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 4, 49, 28, 631569, tzinfo=utc)),
        ),
    ]
