# Generated by Django 2.1.4 on 2019-01-17 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0019_auto_20190111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 8, 12, 10, 798415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_video_id',
            field=models.IntegerField(null=True),
        ),
    ]
