# Generated by Django 2.1.4 on 2019-01-18 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0021_auto_20190117_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 7, 9, 35, 464585, tzinfo=utc)),
        ),
    ]
