# Generated by Django 2.1.4 on 2019-01-23 03:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0022_auto_20190118_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 3, 5, 23, 664707, tzinfo=utc)),
        ),
    ]
