# Generated by Django 2.1.4 on 2019-01-23 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0023_auto_20190123_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-blog_create_time',), 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 6, 33, 25, 226620, tzinfo=utc)),
        ),
    ]
