# Generated by Django 2.1.4 on 2018-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20181224_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='1980-01-01', max_length=20),
        ),
    ]
