# Generated by Django 2.1.4 on 2019-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181224_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', upload_to='avatar/%Y%m%d'),
        ),
    ]
