# Generated by Django 2.1.4 on 2019-01-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190118_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
    ]
