# Generated by Django 2.1.4 on 2019-01-03 04:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_blog', '0016_auto_20190103_1249'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=256)),
                ('comment_time', models.DateTimeField(default=datetime.datetime(2019, 1, 3, 4, 49, 28, 647444, tzinfo=utc))),
                ('comment_blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_blog.Blog')),
                ('comment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'ordering': ('-comment_time',),
            },
        ),
    ]
