# Generated by Django 2.1.4 on 2019-01-23 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('BBS_index', '0001_initial'),
        ('comment', '0002_auto_20190103_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BBScomment_content', models.CharField(max_length=256)),
                ('BBScomment_time', models.DateTimeField(auto_now_add=True)),
                ('BBScomment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBS_index.Topic')),
                ('BBScomment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '帖子评论',
                'verbose_name_plural': '帖子评论',
                'ordering': ('BBScomment_time',),
            },
        ),
    ]
