# Generated by Django 2.1.4 on 2019-01-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_bbs_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('comment_time',), 'verbose_name': '博客评论', 'verbose_name_plural': '博客评论'},
        ),
    ]
