# Generated by Django 2.1.4 on 2019-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190123_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_comment',
            name='BBScomment_content',
            field=models.TextField(),
        ),
    ]
